(cl:defpackage omnivelma_msgs-srv
  (:use )
  (:export
   "SETFRICTION"
   "<SETFRICTION-REQUEST>"
   "SETFRICTION-REQUEST"
   "<SETFRICTION-RESPONSE>"
   "SETFRICTION-RESPONSE"
   "SETINERTIA"
   "<SETINERTIA-REQUEST>"
   "SETINERTIA-REQUEST"
   "<SETINERTIA-RESPONSE>"
   "SETINERTIA-RESPONSE"
  ))

