// Generated by gencpp from file omnivelma_msgs/EncodersStamped.msg
// DO NOT EDIT!


#ifndef OMNIVELMA_MSGS_MESSAGE_ENCODERSSTAMPED_H
#define OMNIVELMA_MSGS_MESSAGE_ENCODERSSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <omnivelma_msgs/Encoders.h>

namespace omnivelma_msgs
{
template <class ContainerAllocator>
struct EncodersStamped_
{
  typedef EncodersStamped_<ContainerAllocator> Type;

  EncodersStamped_()
    : header()
    , encoders()  {
    }
  EncodersStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , encoders(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::omnivelma_msgs::Encoders_<ContainerAllocator>  _encoders_type;
  _encoders_type encoders;




  typedef boost::shared_ptr< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> const> ConstPtr;

}; // struct EncodersStamped_

typedef ::omnivelma_msgs::EncodersStamped_<std::allocator<void> > EncodersStamped;

typedef boost::shared_ptr< ::omnivelma_msgs::EncodersStamped > EncodersStampedPtr;
typedef boost::shared_ptr< ::omnivelma_msgs::EncodersStamped const> EncodersStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omnivelma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'omnivelma_msgs': ['/home/pwalas1/catkin_pw/src/omnivelma/src/omnivelma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e154a3842268fb728f92dcf5b5cba110";
  }

  static const char* value(const ::omnivelma_msgs::EncodersStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe154a3842268fb72ULL;
  static const uint64_t static_value2 = 0x8f92dcf5b5cba110ULL;
};

template<class ContainerAllocator>
struct DataType< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omnivelma_msgs/EncodersStamped";
  }

  static const char* value(const ::omnivelma_msgs::EncodersStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
omnivelma_msgs/Encoders encoders\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: omnivelma_msgs/Encoders\n\
omnivelma_msgs/Vels velocity\n\
omnivelma_msgs/Vels angle\n\
\n\
================================================================================\n\
MSG: omnivelma_msgs/Vels\n\
float64 fr\n\
float64 fl\n\
float64 rl\n\
float64 rr\n\
";
  }

  static const char* value(const ::omnivelma_msgs::EncodersStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.encoders);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncodersStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omnivelma_msgs::EncodersStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omnivelma_msgs::EncodersStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encoders: ";
    s << std::endl;
    Printer< ::omnivelma_msgs::Encoders_<ContainerAllocator> >::stream(s, indent + "  ", v.encoders);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIVELMA_MSGS_MESSAGE_ENCODERSSTAMPED_H
