// Generated by gencpp from file omnivelma_msgs/Encoders.msg
// DO NOT EDIT!


#ifndef OMNIVELMA_MSGS_MESSAGE_ENCODERS_H
#define OMNIVELMA_MSGS_MESSAGE_ENCODERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <omnivelma_msgs/Vels.h>
#include <omnivelma_msgs/Vels.h>

namespace omnivelma_msgs
{
template <class ContainerAllocator>
struct Encoders_
{
  typedef Encoders_<ContainerAllocator> Type;

  Encoders_()
    : velocity()
    , angle()  {
    }
  Encoders_(const ContainerAllocator& _alloc)
    : velocity(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::omnivelma_msgs::Vels_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::omnivelma_msgs::Vels_<ContainerAllocator>  _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::omnivelma_msgs::Encoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omnivelma_msgs::Encoders_<ContainerAllocator> const> ConstPtr;

}; // struct Encoders_

typedef ::omnivelma_msgs::Encoders_<std::allocator<void> > Encoders;

typedef boost::shared_ptr< ::omnivelma_msgs::Encoders > EncodersPtr;
typedef boost::shared_ptr< ::omnivelma_msgs::Encoders const> EncodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omnivelma_msgs::Encoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omnivelma_msgs::Encoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omnivelma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'omnivelma_msgs': ['/home/pwalas1/catkin_pw/src/omnivelma/src/omnivelma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::Encoders_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a14e6d34d7cb73a32c3f00a409af72f0";
  }

  static const char* value(const ::omnivelma_msgs::Encoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa14e6d34d7cb73a3ULL;
  static const uint64_t static_value2 = 0x2c3f00a409af72f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omnivelma_msgs/Encoders";
  }

  static const char* value(const ::omnivelma_msgs::Encoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omnivelma_msgs/Vels velocity\n\
omnivelma_msgs/Vels angle\n\
\n\
================================================================================\n\
MSG: omnivelma_msgs/Vels\n\
float64 fr\n\
float64 fl\n\
float64 rl\n\
float64 rr\n\
";
  }

  static const char* value(const ::omnivelma_msgs::Encoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omnivelma_msgs::Encoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omnivelma_msgs::Encoders_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::omnivelma_msgs::Vels_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "angle: ";
    s << std::endl;
    Printer< ::omnivelma_msgs::Vels_<ContainerAllocator> >::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIVELMA_MSGS_MESSAGE_ENCODERS_H
