// Generated by gencpp from file omnivelma_msgs/RelativeStamped.msg
// DO NOT EDIT!


#ifndef OMNIVELMA_MSGS_MESSAGE_RELATIVESTAMPED_H
#define OMNIVELMA_MSGS_MESSAGE_RELATIVESTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <omnivelma_msgs/Relative.h>

namespace omnivelma_msgs
{
template <class ContainerAllocator>
struct RelativeStamped_
{
  typedef RelativeStamped_<ContainerAllocator> Type;

  RelativeStamped_()
    : header()
    , relative()  {
    }
  RelativeStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , relative(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::omnivelma_msgs::Relative_<ContainerAllocator>  _relative_type;
  _relative_type relative;




  typedef boost::shared_ptr< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> const> ConstPtr;

}; // struct RelativeStamped_

typedef ::omnivelma_msgs::RelativeStamped_<std::allocator<void> > RelativeStamped;

typedef boost::shared_ptr< ::omnivelma_msgs::RelativeStamped > RelativeStampedPtr;
typedef boost::shared_ptr< ::omnivelma_msgs::RelativeStamped const> RelativeStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omnivelma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'omnivelma_msgs': ['/home/pwalas1/catkin_pw/src/omnivelma/src/omnivelma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b34c76dbe1f5aa71792100dda300765";
  }

  static const char* value(const ::omnivelma_msgs::RelativeStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b34c76dbe1f5aa7ULL;
  static const uint64_t static_value2 = 0x1792100dda300765ULL;
};

template<class ContainerAllocator>
struct DataType< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omnivelma_msgs/RelativeStamped";
  }

  static const char* value(const ::omnivelma_msgs::RelativeStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
omnivelma_msgs/Relative relative\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: omnivelma_msgs/Relative\n\
float64 distance\n\
float64 angle\n\
";
  }

  static const char* value(const ::omnivelma_msgs::RelativeStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.relative);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelativeStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omnivelma_msgs::RelativeStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omnivelma_msgs::RelativeStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "relative: ";
    s << std::endl;
    Printer< ::omnivelma_msgs::Relative_<ContainerAllocator> >::stream(s, indent + "  ", v.relative);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIVELMA_MSGS_MESSAGE_RELATIVESTAMPED_H
