// Generated by gencpp from file omnivelma_msgs/Relative.msg
// DO NOT EDIT!


#ifndef OMNIVELMA_MSGS_MESSAGE_RELATIVE_H
#define OMNIVELMA_MSGS_MESSAGE_RELATIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omnivelma_msgs
{
template <class ContainerAllocator>
struct Relative_
{
  typedef Relative_<ContainerAllocator> Type;

  Relative_()
    : distance(0.0)
    , angle(0.0)  {
    }
  Relative_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;

   typedef double _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::omnivelma_msgs::Relative_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omnivelma_msgs::Relative_<ContainerAllocator> const> ConstPtr;

}; // struct Relative_

typedef ::omnivelma_msgs::Relative_<std::allocator<void> > Relative;

typedef boost::shared_ptr< ::omnivelma_msgs::Relative > RelativePtr;
typedef boost::shared_ptr< ::omnivelma_msgs::Relative const> RelativeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omnivelma_msgs::Relative_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omnivelma_msgs::Relative_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omnivelma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'omnivelma_msgs': ['/home/pwalas1/catkin_pw/src/omnivelma/src/omnivelma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::Relative_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::Relative_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::Relative_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::Relative_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::Relative_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::Relative_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omnivelma_msgs::Relative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f1d53743f4592ee455aa3eaf9019457";
  }

  static const char* value(const ::omnivelma_msgs::Relative_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f1d53743f4592eeULL;
  static const uint64_t static_value2 = 0x455aa3eaf9019457ULL;
};

template<class ContainerAllocator>
struct DataType< ::omnivelma_msgs::Relative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omnivelma_msgs/Relative";
  }

  static const char* value(const ::omnivelma_msgs::Relative_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omnivelma_msgs::Relative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n\
float64 angle\n\
";
  }

  static const char* value(const ::omnivelma_msgs::Relative_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omnivelma_msgs::Relative_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Relative_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omnivelma_msgs::Relative_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omnivelma_msgs::Relative_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIVELMA_MSGS_MESSAGE_RELATIVE_H
