// Generated by gencpp from file omnivelma_msgs/SetFrictionRequest.msg
// DO NOT EDIT!


#ifndef OMNIVELMA_MSGS_MESSAGE_SETFRICTIONREQUEST_H
#define OMNIVELMA_MSGS_MESSAGE_SETFRICTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omnivelma_msgs
{
template <class ContainerAllocator>
struct SetFrictionRequest_
{
  typedef SetFrictionRequest_<ContainerAllocator> Type;

  SetFrictionRequest_()
    : mu1(0.0)
    , mu2(0.0)  {
    }
  SetFrictionRequest_(const ContainerAllocator& _alloc)
    : mu1(0.0)
    , mu2(0.0)  {
  (void)_alloc;
    }



   typedef double _mu1_type;
  _mu1_type mu1;

   typedef double _mu2_type;
  _mu2_type mu2;




  typedef boost::shared_ptr< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFrictionRequest_

typedef ::omnivelma_msgs::SetFrictionRequest_<std::allocator<void> > SetFrictionRequest;

typedef boost::shared_ptr< ::omnivelma_msgs::SetFrictionRequest > SetFrictionRequestPtr;
typedef boost::shared_ptr< ::omnivelma_msgs::SetFrictionRequest const> SetFrictionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omnivelma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'omnivelma_msgs': ['/home/pwalas1/catkin_pw/src/omnivelma/src/omnivelma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4a6558102ac1181f82735851ff5553b";
  }

  static const char* value(const ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4a6558102ac1181ULL;
  static const uint64_t static_value2 = 0xf82735851ff5553bULL;
};

template<class ContainerAllocator>
struct DataType< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omnivelma_msgs/SetFrictionRequest";
  }

  static const char* value(const ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 mu1\n\
float64 mu2\n\
";
  }

  static const char* value(const ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mu1);
      stream.next(m.mu2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFrictionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omnivelma_msgs::SetFrictionRequest_<ContainerAllocator>& v)
  {
    s << indent << "mu1: ";
    Printer<double>::stream(s, indent + "  ", v.mu1);
    s << indent << "mu2: ";
    Printer<double>::stream(s, indent + "  ", v.mu2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIVELMA_MSGS_MESSAGE_SETFRICTIONREQUEST_H
