// Generated by gencpp from file omnivelma_msgs/SetFriction.msg
// DO NOT EDIT!


#ifndef OMNIVELMA_MSGS_MESSAGE_SETFRICTION_H
#define OMNIVELMA_MSGS_MESSAGE_SETFRICTION_H

#include <ros/service_traits.h>


#include <omnivelma_msgs/SetFrictionRequest.h>
#include <omnivelma_msgs/SetFrictionResponse.h>


namespace omnivelma_msgs
{

struct SetFriction
{

typedef SetFrictionRequest Request;
typedef SetFrictionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFriction
} // namespace omnivelma_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::omnivelma_msgs::SetFriction > {
  static const char* value()
  {
    return "f4a6558102ac1181f82735851ff5553b";
  }

  static const char* value(const ::omnivelma_msgs::SetFriction&) { return value(); }
};

template<>
struct DataType< ::omnivelma_msgs::SetFriction > {
  static const char* value()
  {
    return "omnivelma_msgs/SetFriction";
  }

  static const char* value(const ::omnivelma_msgs::SetFriction&) { return value(); }
};


// service_traits::MD5Sum< ::omnivelma_msgs::SetFrictionRequest> should match 
// service_traits::MD5Sum< ::omnivelma_msgs::SetFriction > 
template<>
struct MD5Sum< ::omnivelma_msgs::SetFrictionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::omnivelma_msgs::SetFriction >::value();
  }
  static const char* value(const ::omnivelma_msgs::SetFrictionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::omnivelma_msgs::SetFrictionRequest> should match 
// service_traits::DataType< ::omnivelma_msgs::SetFriction > 
template<>
struct DataType< ::omnivelma_msgs::SetFrictionRequest>
{
  static const char* value()
  {
    return DataType< ::omnivelma_msgs::SetFriction >::value();
  }
  static const char* value(const ::omnivelma_msgs::SetFrictionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::omnivelma_msgs::SetFrictionResponse> should match 
// service_traits::MD5Sum< ::omnivelma_msgs::SetFriction > 
template<>
struct MD5Sum< ::omnivelma_msgs::SetFrictionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::omnivelma_msgs::SetFriction >::value();
  }
  static const char* value(const ::omnivelma_msgs::SetFrictionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::omnivelma_msgs::SetFrictionResponse> should match 
// service_traits::DataType< ::omnivelma_msgs::SetFriction > 
template<>
struct DataType< ::omnivelma_msgs::SetFrictionResponse>
{
  static const char* value()
  {
    return DataType< ::omnivelma_msgs::SetFriction >::value();
  }
  static const char* value(const ::omnivelma_msgs::SetFrictionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OMNIVELMA_MSGS_MESSAGE_SETFRICTION_H
