// Generated by gencpp from file omnivelma_msgs/SetInertiaRequest.msg
// DO NOT EDIT!


#ifndef OMNIVELMA_MSGS_MESSAGE_SETINERTIAREQUEST_H
#define OMNIVELMA_MSGS_MESSAGE_SETINERTIAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Inertia.h>
#include <geometry_msgs/Inertia.h>
#include <geometry_msgs/Inertia.h>

namespace omnivelma_msgs
{
template <class ContainerAllocator>
struct SetInertiaRequest_
{
  typedef SetInertiaRequest_<ContainerAllocator> Type;

  SetInertiaRequest_()
    : base()
    , front()
    , wheel()  {
    }
  SetInertiaRequest_(const ContainerAllocator& _alloc)
    : base(_alloc)
    , front(_alloc)
    , wheel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Inertia_<ContainerAllocator>  _base_type;
  _base_type base;

   typedef  ::geometry_msgs::Inertia_<ContainerAllocator>  _front_type;
  _front_type front;

   typedef  ::geometry_msgs::Inertia_<ContainerAllocator>  _wheel_type;
  _wheel_type wheel;




  typedef boost::shared_ptr< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetInertiaRequest_

typedef ::omnivelma_msgs::SetInertiaRequest_<std::allocator<void> > SetInertiaRequest;

typedef boost::shared_ptr< ::omnivelma_msgs::SetInertiaRequest > SetInertiaRequestPtr;
typedef boost::shared_ptr< ::omnivelma_msgs::SetInertiaRequest const> SetInertiaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace omnivelma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'omnivelma_msgs': ['/home/pwalas1/catkin_pw/src/omnivelma/src/omnivelma_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e035d263d97e8c32424221cde3ffa8";
  }

  static const char* value(const ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e035d263d97e8cULL;
  static const uint64_t static_value2 = 0x32424221cde3ffa8ULL;
};

template<class ContainerAllocator>
struct DataType< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omnivelma_msgs/SetInertiaRequest";
  }

  static const char* value(const ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Inertia base\n\
geometry_msgs/Inertia front\n\
geometry_msgs/Inertia wheel\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Inertia\n\
# Mass [kg]\n\
float64 m\n\
\n\
# Center of mass [m]\n\
geometry_msgs/Vector3 com\n\
\n\
# Inertia Tensor [kg-m^2]\n\
#     | ixx ixy ixz |\n\
# I = | ixy iyy iyz |\n\
#     | ixz iyz izz |\n\
float64 ixx\n\
float64 ixy\n\
float64 ixz\n\
float64 iyy\n\
float64 iyz\n\
float64 izz\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base);
      stream.next(m.front);
      stream.next(m.wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInertiaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omnivelma_msgs::SetInertiaRequest_<ContainerAllocator>& v)
  {
    s << indent << "base: ";
    s << std::endl;
    Printer< ::geometry_msgs::Inertia_<ContainerAllocator> >::stream(s, indent + "  ", v.base);
    s << indent << "front: ";
    s << std::endl;
    Printer< ::geometry_msgs::Inertia_<ContainerAllocator> >::stream(s, indent + "  ", v.front);
    s << indent << "wheel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Inertia_<ContainerAllocator> >::stream(s, indent + "  ", v.wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMNIVELMA_MSGS_MESSAGE_SETINERTIAREQUEST_H
