obstacle_range: 3.3
raycast_range: 10.0
min_obstacle_height: 0.0
#wpisz poprawne dane od footprinta!
#The footprint parameter describes the shape and size of your robot, in meters. 0,0 is assumed to be the #turning center of your robot, and you define the corners of your robot relative to that center. +X is #forward, +Y is to the left, as defined in
#footprint: [ [0.38, 0.38], [-0.38, 0.38], [-0.38, -0.38], [0.38, -0.38] ]
footprint: [ [0.01, 0.01], [-0.01, 0.01], [-0.01, -0.01], [0.01, -0.01] ]
footprint_padding: 0.01

sensor:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: { sensor_frame: omnivelma , data_type: LaserScan, topic: /scan, marking : true, clearing: true, raytrace_range: 3.5, obstacle_range: 3.5 }

social:
  enabled: True
  cutoff: 30.0
  amplitude: 254.0
  covariance: 1.25
  factor: 7.0
  keep_time: 0.1